FROM golang:1.14-alpine as build
RUN apk add --no-cache make gcc musl-dev linux-headers git
ENV GOPATH=/go
WORKDIR /go
COPY . /go/src/github.com/ethereum/go-ethereum/
RUN mkdir -p /go/bin && \
    go build -o /go/bin/geth \
    github.com/ethereum/go-ethereum/cmd/geth

FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=build /go/bin/geth /usr/local/bin/

ENTRYPOINT [ "geth" ]

