FROM golang:1.14 as build
ENV GOPATH=/go
WORKDIR /go
COPY . /go/src/github.com/ethereum/go-ethereum/
RUN mkdir -p /go/bin && \
    go build -o /go/bin/geth \
    github.com/ethereum/go-ethereum/cmd/geth
FROM gcr.io/distroless/base-debian10
COPY --from=build /go/bin/geth /go/bin/geth
ENTRYPOINT [ "/go/bin/geth" ]

